"""Bounded host execution of actual graph/pin traversal and file admission.

UE objects, reflection and JSON objects are stand-ins. Not an Unreal compile,
ExportText/JSON-log integration test, Blueprint load, or immutability proof.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import unittest
from test_weapon_tessellation import compile_run

HERE = Path(__file__).resolve().parent
HEADER = HERE / 'UT4Html5Compat/Source/UT4Html5Compat/Private/WeaponBlueprintReport.h'
PRIVATE = None


def function(source, signature):
    start = source.index(signature)
    opening = source.index('{', start)
    depth = 1
    end = opening + 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    return source[start:end]


HOST = r'''
#include <cassert>
#include <string>
#include <vector>
#include <set>
#include <map>
#include <memory>
#include <algorithm>
using int32=int;
using TCHAR=char;
#define TEXT(x) x
struct FString:std::string {using std::string::string;FString(const std::string&s):std::string(s){} FString(){} const char*operator*()const{return c_str();}bool IsEmpty()const{return empty();}int Len()const{return size();}};
template<class T>struct TArray:std::vector<T>{using std::vector<T>::vector;void Add(const T&v){this->push_back(v);}int Num()const{return this->size();}void Append(const TArray<T>&v){this->insert(this->end(),v.begin(),v.end());}bool Contains(const T&v)const{return std::find(this->begin(),this->end(),v)!=this->end();}};
template<class T>struct TSet:std::set<T>{void Add(const T&v){this->insert(v);}int Num()const{return this->size();}bool Contains(const T&v)const{return this->count(v);}};
template<class T>using TSharedPtr=std::shared_ptr<T>;
template<class T>TSharedPtr<T>MakeShareable(T*p){return TSharedPtr<T>(p);}
struct FJsonObject;
struct FJsonValue{FString text;virtual ~FJsonValue(){};};
struct FJsonValueString:FJsonValue{FJsonValueString(const FString&s){text=s;}};
struct FJsonObject{
 std::map<FString,FString> strings;std::map<FString,int> numbers;std::map<FString,bool> flags;
 std::map<FString,TSharedPtr<FJsonObject>> objects;std::map<FString,TArray<TSharedPtr<FJsonValue>>> arrays;
 void SetStringField(const TCHAR*k,const FString&v){strings[k]=v;}void SetNumberField(const TCHAR*k,int v){numbers[k]=v;}
 void SetBoolField(const TCHAR*k,bool v){flags[k]=v;}void SetObjectField(const TCHAR*k,TSharedPtr<FJsonObject>v){objects[k]=v;}
 void SetArrayField(const TCHAR*k,const TArray<TSharedPtr<FJsonValue>>&v){arrays[k]=v;}bool HasField(const TCHAR*k){return strings.count(k);}
};
struct UProperty{int ArrayDim=1;};
struct UClass{TArray<UProperty*> fields;bool hasReference=false;};
struct UObject{FString path;UClass cls;TSharedPtr<FJsonObject> properties=MakeShareable(new FJsonObject);FString GetPathName()const{return path;}UObject*GetClass(){return this;}};
// Reflection iterator stand-in uses each object's synthetic declaration list.
template<class T>struct TFieldIterator{UObject*o;int i=0;TFieldIterator(UObject*x):o(x){}explicit operator bool()const{return i<o->cls.fields.Num();}void operator++(){++i;}T*operator*(){return o->cls.fields[i];}};
template<class T>T*FindField(UObject*o,const TCHAR*k){static T p;return o->cls.hasReference&&FString(k)=="FunctionReference"?&p:nullptr;}
TSharedPtr<FJsonObject>MRProperties(UObject*o,bool all){assert(all);return o->properties;}
struct Text{FString value;FString ToString()const{return value;}};
struct Guid:Text{bool IsValid()const{return !value.empty();}};
template<class T>struct Weak{T*ptr=nullptr;T*Get()const{return ptr;}};
struct FEdGraphPinType{
 FString PinCategory,PinSubCategory;Weak<UObject>PinSubCategoryObject;
 struct{UObject*MemberParent=nullptr;Text MemberName;Guid MemberGuid;}PinSubCategoryMemberReference;
 struct{FString TerminalCategory,TerminalSubCategory;Weak<UObject>TerminalSubCategoryObject;bool bTerminalIsConst=false,bTerminalIsWeakPointer=false;}PinValueType;
 bool bIsArray=false,bIsSet=false,bIsMap=false,bIsReference=false,bIsConst=false,bIsWeakPointer=false;
};
struct UBlueprint;struct UEdGraph;struct UEdGraphNode;
enum Direction{EGPD_Input,EGPD_Output};
struct UEdGraphPin{
 UEdGraphNode*owner=nullptr;Guid PinId;FString PinName,DefaultValue,AutogeneratedDefaultValue;Direction Direction=EGPD_Input;
 FEdGraphPinType PinType;UObject*DefaultObject=nullptr;Text DefaultTextValue;
 TArray<UEdGraphPin*>LinkedTo,SubPins;UEdGraphPin*ParentPin=nullptr,*ReferencePassThroughConnection=nullptr;
 bool bWasTrashed=false,bHidden=false,bDefaultValueIsIgnored=false,bDefaultValueIsReadOnly=false,bNotConnectable=false;
 UEdGraphNode*GetOwningNodeUnchecked()const{return owner;}
};
struct UEdGraphNode:UObject{UEdGraph*graph=nullptr;Guid NodeGuid;TArray<UEdGraphPin*>Pins;TArray<int>DeprecatedPins;UEdGraph*GetGraph(){return graph;}bool IsIn(UBlueprint*b)const;};
struct UEdGraph:UObject{UBlueprint*bp=nullptr;TArray<UEdGraphNode*>Nodes;TArray<UEdGraph*>SubGraphs;Guid GraphGuid;bool IsIn(UBlueprint*b){return bp==b;}};
bool UEdGraphNode::IsIn(UBlueprint*b)const{return graph&&graph->bp==b;}
struct UBlueprint:UObject{TArray<UEdGraph*>UbergraphPages,FunctionGraphs,MacroGraphs,DelegateSignatureGraphs;TArray<int>ImplementedInterfaces;};
struct FWBPOutput{
 int Graphs=0,Nodes=0,Pins=0,Links=0,limit=10000;
 std::vector<std::pair<std::string,TSharedPtr<FJsonObject>>> rows;
 bool Emit(TSharedPtr<FJsonObject>j,const TCHAR*kind){if(int(rows.size())>=limit)return false;rows.push_back({kind,j});return true;}
};
'''


class BlueprintReport(unittest.TestCase):
    def test_fixed_scope_observation_and_before_after_contract(self):
        s = HEADER.read_text()
        self.assertEqual(re.findall(r'TEXT\("(/Game/[^"\n]+)"\)', s), [
            '/Game/RestrictedAssets/Weapons/GrenadeLauncher/BP_GrenadeLauncher',
            '/Game/RestrictedAssets/Weapons/GrenadeLauncher/BP_GrenadeLauncher_Attach'])
        for forbidden in ('SavePackage(', 'ClearDirty', 'SetDirtyFlag', 'CompileBlueprint(', 'RegenerateClass(',
                          'SpawnActor', 'ProcessEvent(', 'NewObject<', 'GetDefaultObject(', 'UK2Node', '#include'):
            self.assertNotIn(forbidden, s)
        self.assertIn('BlueprintOriginalContent=', s)
        self.assertLess(s.index("OriginalContent[1] != ':'"), s.index('OriginalContent = Full(OriginalContent)'))
        self.assertIn('COMPAT_WEAPON_BLUEPRINT %s', s)
        self.assertIn('ut4-weapon-blueprint-v1', s)
        self.assertIn('TEXT("global_immutability_proven"), false', s)
        self.assertIn('TEXT("compile_on_load_disabled"), false', s)
        self.assertIn('LOAD_NoRedirects)', s)
        self.assertLess(s.index('FindPackage(nullptr, *P)'), s.index('LoadObject<UBlueprint>'))
        self.assertLess(s.index('for (const FWBPFile& F : Files) if (!F.Check())'), s.index('LoadObject<UBlueprint>'))
        self.assertLess(s.index('if (!Files[I].Check())'), s.index('Out.Emit(Done, TEXT("complete"))'))
        self.assertIn('B->GetClass() != UBlueprint::StaticClass()', s)
        self.assertIn('B->GeneratedClass->ClassGeneratedBy != B', s)
        self.assertIn('TEXT("/Script/Engine.BlueprintGeneratedClass")', s)
        self.assertIn('B->ImplementedInterfaces.Num()', s)
        self.assertIn('Text.Len() > 65536', s)
        self.assertIn('8 * 1024 * 1024 - Text.Len()', s)
        for name in ('FunctionReference', 'VariableReference', 'MacroGraphReference'):
            self.assertIn('TEXT("' + name + '")', s)
        self.assertIn('default_text_display', s)  # No claim to serialize FText identity/history.

    def test_actual_graph_traversal_and_pin_fields(self):
        s = HEADER.read_text()
        signatures = ('static FString WBPPath', 'static TSharedPtr<FJsonObject> WBPObject',
                      'static TSharedPtr<FJsonObject> WBPPinType', 'static FString WBPPinId',
                      'static bool WBPProperties', 'static bool WBPGraphs')
        code = HOST + '\n'.join(function(s, sig) for sig in signatures) + r'''
int main(){
 for(int scenario=0;scenario<21;++scenario){
  UBlueprint b;UEdGraph g,h;UEdGraphNode n;UEdGraphPin p,q;UObject asset;UProperty prop;
  b.path="/BP";g.path="/BP/G";h.path="/BP/H";g.bp=h.bp=&b;g.GraphGuid.value="g";h.GraphGuid.value="h";
  b.UbergraphPages.Add(&g);b.FunctionGraphs.Add(&h);b.MacroGraphs.Add(&g);b.DelegateSignatureGraphs.Add(&h);
  g.SubGraphs.Add(&h);h.SubGraphs.Add(&g); // Cycle and shared roots emit each graph once.
  n.path="/BP/G/N";n.graph=&g;n.NodeGuid.value="node";g.Nodes.Add(&n);
  n.cls.fields.Add(&prop);n.cls.hasReference=true;
  for(const char*k:{"FunctionReference","VariableReference","MacroGraphReference"})n.properties->SetStringField(k,"external unresolved reference");
  p.owner=q.owner=&n;p.PinId.value="p";q.PinId.value="q";n.Pins.Add(&p);n.Pins.Add(&q);
  p.PinName="texture";p.DefaultValue="quoted \"name\"\nnext";p.AutogeneratedDefaultValue="original";
  asset.path="/Other/Asset";p.DefaultObject=&asset;p.DefaultTextValue.value="display text";
  p.PinType.PinCategory="map";p.PinType.bIsMap=true;p.PinType.PinValueType.TerminalCategory="object";
  p.PinType.PinValueType.TerminalSubCategoryObject.ptr=&asset;p.PinType.PinValueType.bTerminalIsWeakPointer=true;
  p.PinType.PinSubCategoryMemberReference.MemberName.value="delegate";p.PinType.PinSubCategoryMemberReference.MemberParent=&asset;
  p.LinkedTo.Add(&q);q.LinkedTo.Add(&p);q.Direction=EGPD_Output;p.SubPins.Add(&q);q.ParentPin=&p;p.ReferencePassThroughConnection=&q;
  FWBPOutput out;
  if(scenario==1)b.ImplementedInterfaces.Add(1);
  if(scenario==2)g.SubGraphs.Add(nullptr);
  if(scenario==3)h.bp=nullptr;
  if(scenario==4)g.Nodes.Add(nullptr);
  if(scenario==5)n.graph=&h;
  if(scenario==6)g.Nodes.Add(&n);
  if(scenario==7)n.DeprecatedPins.Add(1);
  if(scenario==8)p.owner=nullptr;
  if(scenario==9)p.bWasTrashed=true;
  if(scenario==10)q.PinId.value="p";
  if(scenario==11)q.LinkedTo.clear();
  if(scenario==12)q.ParentPin=nullptr;
  if(scenario==13)p.PinId.value="";
  if(scenario==14)out.Nodes=4096;
  if(scenario==15)out.Pins=32768;
  if(scenario==16)out.Links=131072;
  if(scenario==17)out.limit=3;
  if(scenario==18)n.properties->strings.erase("FunctionReference");
  if(scenario==19)prop.ArrayDim=513;
  if(scenario==20){n.Pins.pop_back();p.SubPins.clear();q.ParentPin=nullptr;} // Linked local pin omitted from the captured graph.
  assert(WBPGraphs(&b,out)==(scenario==0));
  if(scenario==0){
   assert(out.Graphs==2&&out.Nodes==1&&out.Pins==2&&out.Links==2);
   int pins=0,nodes=0;
   for(auto&row:out.rows){auto j=row.second;
    if(row.first=="node"){++nodes;assert(j->objects["properties"]->strings["FunctionReference"]=="external unresolved reference");}
    if(row.first=="pin"){++pins;if(j->strings["name"]!="texture")continue;
     assert(j->strings["id"]=="/BP/G/N:p"&&j->strings["default"]==p.DefaultValue);
     assert(j->strings["autogenerated_default"]=="original"&&j->strings["default_object"]=="/Other/Asset");
     assert(j->strings["default_text_display"]=="display text");
     assert(j->strings["reference_passthrough"]=="/BP/G/N:q");
     assert(j->arrays["links"].size()==1&&j->arrays["links"][0]->text=="/BP/G/N:q");
     assert(j->arrays["subpins"].size()==1);
     auto t=j->objects["type"];assert(t->flags["map"]&&t->objects["map_value"]->strings["object"]=="/Other/Asset");
     assert(t->objects["map_value"]->flags["weak"]&&t->strings["member_name"]=="delegate");
    }
   }assert(pins==2&&nodes==1);
  }
 }
}
'''
        compile_run(code)

    def test_actual_file_check_rejects_drift_and_bounds(self):
        block = function(HEADER.read_text(), 'struct FWBPFile') + ';'
        code = r'''
#include <cassert>
#include <string>
using int32=int;
struct FString:std::string{using std::string::string;FString(){}const char*operator*()const{return c_str();}int Len()const{return size();}};
int scenario=0,hashes=0;
bool Physical(const FString&,bool missing){assert(!missing);return scenario!=1;}
FString Full(const FString&s){return s;}
struct FPackageName{static bool DoesPackageExist(const FString&,void*,FString*out){*out=scenario==2?"changed":"selected";return scenario!=3;}};
struct IFileManager{static IFileManager&Get(){static IFileManager f;return f;}long FileSize(const char*p){bool original=std::string(p)=="original";if((scenario==4&&original)||(scenario==5&&!original))return -1;if((scenario==6&&original)||(scenario==7&&!original))return 64*1024*1024+1;return 100;}};
FString HashFile(const FString&p){++hashes;return ((scenario==8&&p=="original")||(scenario==9&&p=="selected"))?"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";}
BLOCK
int main(){for(scenario=0;scenario<=10;++scenario){FWBPFile f;f.Package="/Game/BP";f.Original="original";f.Selected="selected";f.Hash=scenario==10?"":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";hashes=0;assert(f.Check()==(scenario==0));if(scenario>=1&&scenario<=7)assert(hashes==0);}}
'''
        compile_run(code.replace('BLOCK', block))

    def test_optional_pinned_blueprint_api(self):
        if PRIVATE is None:
            self.skipTest('pass --private-source for captured native declarations')
        pins = json.loads((PRIVATE / 'pins.json').read_text('utf-8-sig'))
        for name in ('Blueprint.h', 'EdGraph.h', 'EdGraphNode.h', 'EdGraphPin.h', 'Blueprint.cpp', 'ObjectMacros.h'):
            self.assertEqual(hashlib.sha256((PRIVATE / name).read_bytes()).hexdigest(), pins[name])
        self.assertNotIn('LOAD_DisableCompileOnLoad', (PRIVATE / 'ObjectMacros.h').read_text())
        self.assertIn('LOAD_NoRedirects', (PRIVATE / 'ObjectMacros.h').read_text())
        self.assertIn('GetOwningNodeUnchecked() const { return OwningNode; }', (PRIVATE / 'EdGraphPin.h').read_text())


if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument('--private-source', type=Path)
    args, rest = parser.parse_known_args()
    PRIVATE = args.private_source
    unittest.main(argv=[__file__, *rest])
